# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cotizcesar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-lambda-example
service: serverless-lambda-example

package:
  individually: true

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: serverless-lambda-example
      description: Serverless Lambda Example
      compatibleRuntimes:
        - python3.10

functions:
  app:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - "env/**"
        - ".env/**"
        - "__pycache__/**"
        - "node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}